import {
  EduKito,
  Eduvibe,
  EduWell,
  RedOnion,
  PatoRes,
  CreativeAgency,
  CreativeAgency2,
  CreativeAgency3,
  CreativeAgency4,
  EduKito2,
  EduKito3,
  EduKito4,
  Eduvibe2,
  Eduvibe3,
  Eduvibe4,
  RedOnion2,
  RedOnion3,
  RedOnion4,
  PatoRes2,
  PatoRes3,
  PatoRes4,
  Promptopia,
  Promptopia2,
  Promptopia3,
  Promptopia4,
  threads,
  threads2,
  threads3,
  threads4,
} from "../assets/img";

export const ProjectsList1 = [
  {
    id: 1,
    title: "Creative Agency",
    description: "Design & Development",
    imgUrl: CreativeAgency,
    link: "https://creative-agency-client.vercel.app",
    images: [CreativeAgency, CreativeAgency2, CreativeAgency3, CreativeAgency4],
    gitHubLink: "https://github.com/akibbhuiyan/creative-agency",
    projDes: [
      "Users can log in using their email and password or with their Google account.",
      "After logging in, users are directed to their dashboard. Here, they can view their enrolled courses, payment history, and other account details.",
      "The website features a course listing page that displays all available courses.",
      "The course details page provides more information about a course,  ",
      "Users can also see reviews from other students who have taken the course.",
      "Users can enroll in a course by clicking on the 'Enroll Now' button on the course details page. ",
      "The website has an admin dashboard that allows the administrator to manage courses, enrollments, and payments. The admin can add new courses, update course details, view enrollment and payment details, and manage user accounts.",
      "Users can leave reviews for courses they have taken. These reviews are displayed on the course details page and help other users make informed decisions.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 2,
    title: "EduKito",
    description: "Design & Development",
    imgUrl: EduKito,
    link: "https://edukito.vercel.app/",
    images: [EduKito, EduKito2, EduKito3, EduKito4],
    gitHubLink: "https://github.com/akibbhuiyan/edukito",
    projDes: [
      "react-query - used for fetching data from server and loading state and refetch",
      "axios - Explore the use of axios and used to get server data.",
      "date-fns - used to format the date.",
      "firebase - as authentication service. And to host this website.",
      "react-router-dom - Using react-router-dom make all the route for this project.",
      "react-hook-form - Using get form values, show error message and some basic validation.",
      "react-hot-toast - To show beautiful message for user.",
      "react-icons - Used for site icon.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 3,
    title: "EduVibe",
    description: "Design & Development",
    imgUrl: Eduvibe,
    link: "https://edu-vibe.vercel.app/",
    images: [Eduvibe, Eduvibe2, Eduvibe3, Eduvibe4],
    gitHubLink: "https://github.com/akibbhuiyan/eduVibe",
    projDes: [
      "Users can create an account, log in, and enroll in courses.",
      "The website features a dashboard where users can manage their courses",
      "Private routing for authenticated users is implemented using React Router.",
      "Firebase handles user authentication.",
      "The application leverages the MERN stack for efficient development and deployment",
      "The website has a clean and modern user interface for optimal user experience.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 4,
    title: "Red Onion",
    description: "Design & Development",
    imgUrl: RedOnion,
    link: "https://red-onion-eosin.vercel.app/",
    images: [RedOnion, RedOnion2, RedOnion3, RedOnion4],
    gitHubLink: "https://github.com/akibbhuiyan/red-Tomato",
    projDes: [
      "User can select different categories for Food",
      "User can select quantity and add the food to cart",
      "Users can create an account, log in, and order for Food",
      "The website features a dashboard where users can manage their Order",
      "Private routing for authenticated users is implemented using React Router.",
      "Firebase handles user authentication.",
      "The application leverages the MERN stack for efficient development and deployment",
      "The website has a clean and modern user interface for optimal user experience.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },

  {
    id: 5,
    title: "Pato Restaurent",
    description: "Design & Development",
    imgUrl: PatoRes,
    link: "https://pato-restaurent.vercel.app/",
    images: [PatoRes, PatoRes2, PatoRes3, PatoRes4],
    gitHubLink: "https://github.com/akibbhuiyan/Pato-Restaurent",
    projDes: [
      "User can select different categories for Food",
      "User can select quantity and add the food to cart",
      "Users can create an account, log in, and order for Food",
      "The website features a dashboard where users can manage their Order",
      "Private routing for authenticated users is implemented using React Router.",
      "Firebase handles user authentication.",
      "The application leverages the MERN stack for efficient development and deployment",
      "The website has a clean and modern user interface for optimal user experience.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 6,
    title: "Promptopia",
    description: "Design & Development",
    imgUrl: Promptopia,
    link: "https://promptopia-jade-delta.vercel.app",
    images: [Promptopia, Promptopia2, Promptopia3, Promptopia4],
    gitHubLink: "https://github.com/akibbhuiyan/Pato-Restaurent",
    projDes: [
      "User Authentication: Securely sign up and log in using NextAuth, ensuring your prompts are safe and your interactions are personalized.",
      "Create and Edit Prompts: Craft your own AI prompts using a user-friendly interface. Edit them later if you want to refine your ideas.",
      "Tagging System: Categorize your prompts with relevant hashtags (#tag) to help others discover them easily.",
      "Explore Prompts: Dive into a diverse collection of AI prompts submitted by the Promptopia community.",
      " Copy Prompts: Like a prompt? Simply copy it to your profile to refer to it later.",
      "Profile Management: Easily manage your shared prompts from your user profile. Edit or delete them whenever you like.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 7,
    title: "Threads",
    description: "Design & Development",
    imgUrl: threads,
    link: "https://threads-two-zeta.vercel.app/",
    images: [threads, threads2, threads3, threads4],
    gitHubLink: "https://github.com/akibbhuiyan/threads/",
    projDes: [
      "User Authentication: Utilizes Clerk for secure user authentication and login.",
      "Post Tweets: Users can post their thoughts in the form of tweets.",
      "Commenting: Engage in conversations by commenting on other users' tweets.",
      "Community Interaction: Join communities, post in them, and interact with like-minded users.",
      "User Search: Easily find and connect with different users.",
      "Community Search: Explore and join various communities of interest.",
      "Profile Management: Users can edit their profiles, update information, and delete their posts and comments.",
      "Mobile Responsive: The website is designed to be responsive and accessible on mobile devices.",
    ],
    technology: [
      "next.13",
      "next-router",
      "react-hook-form",
      "svix",
      "tailwind Css",
      "clerk",
      "nodejs",
      "axios",
      "mongodb  ",
      "typescript",
      "vercel",
      "Express.js",
      "zod",
      "react-icons",
    ],
  },
];
